# Generated by Django 5.1.3 on 2024-12-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('queue_number', models.IntegerField()),
                ('queue_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('window_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['Nurse', 'Physician', 'Dentist']}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
