# Generated by Django 5.1.3 on 2024-12-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Dental', 'Dental'), ('Other', 'Other')], max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.TextField()),
                ('HR', models.CharField(max_length=10)),
                ('RR', models.CharField(max_length=10)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bp', models.CharField(max_length=20)),
                ('pain_scale', models.IntegerField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('initial_diagnosis', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['Nurse', 'Physician', 'Dentist']}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
