# Generated by Django 5.1.4 on 2025-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_account_is_patient_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='role',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Faculty', 'Faculty'), ('Personnel', 'Personnel')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
