# Generated by Django 5.1.4 on 2025-01-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_appointment_appointment_id_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='queue_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Faculty', 'Faculty'), ('Personnel', 'Personnel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
