# Generated by Django 5.1.4 on 2025-01-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='queue_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='role',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('General', 'General'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Specialist', 'Specialist')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
