# Generated by Django 5.1.4 on 2025-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_appointment_id_remove_appointment_queue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
