# Generated by Django 5.1.4 on 2025-01-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_appointment_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='role',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Faculty', 'Faculty'), ('Personnel', 'Personnel')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
