# Generated by Django 5.1.4 on 2025-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_appointment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='classification',
            field=models.CharField(choices=[('Personnel', 'Personnel'), ('Faculty', 'Faculty'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
