# Generated by Django 5.1.4 on 2025-01-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_patient_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
